### PR TITLE
Support for GAN Smart Timer using its Bluetooth protocol

### PR DESCRIPTION
**Pull request by afedotov**
Hello!

Sadly original csTimer repository is inactive and its author gone missing(( Future of csTimer uncertain. Domain cstimer.net is going to expire in one month. The original csTimer may suddenly disappear.

I see you deploy latest version of csTimer under cubing.net umbrella, and I hope it can live long and prosper there.

Recently I've created typescript library to interact with GAN Smart Timer using its bluetooth protocol: https://www.npmjs.com/package/gan-web-bluetooth.
And next step I did is adding support for GAN Smart Timer to csTimer. This PR is about it.

For demo and testing purposes I build static version of updated csTimer and deploy it under github pages here: https://afedotov.github.io/cstimer/
But such static builds of csTimer do not have server-side features and can support only one prebuild language. I hope you can incorporate this feature in version deployed on cubing.net as it more likely to become developing successor of original csTimer.

BTW... I see you modify original Makefile to use gsed instead of sed. I think it is better to add alias right in your environment than change Makefile because this can broke builds on other environments which does not have gsed. And my way here is just use Docker, moreover it adds isolation from host system. I've added some scripts to repo that can help build and run csTimer locally using proper containers.

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks! If Chen Shuang has indeed moved on from maintaining his projects, this would be a good time to start making it a community-maintainable project.

However, regarding this specific change, we already have our own implementation of Gan Timer support in cubing.js:

- https://js.cubing.net/cubing/api/functions/bluetooth.connectSmartTimer.html
- https://github.com/cubing/cubing.js/blob/fdf6f0ae4af29de4aced2a02307f2e1ed78ced63/src/cubing/bluetooth/smart-timer/GanTimer.ts

Do you think you'd be able to use/build on that?

**Comment by afedotov** [comment]
Looking at cubing.js implementation is first what I did in the beginning of the journey. But it is far behind capabilities of GAN Smart Timer bluetooth protocol. Using the read-type (pull-like) bluetooth characteristic in polling fashion is not how it should work, and it actually contains only latest time values. Moreover this infinite polling loop on that type of characteristic causes browser freeze and crash.

Regarding csTimer, it is designed using very old fashioned JavaScript, using IIFE and closure compiler. There is no any module system, external npm packages and node.js build tools used in the project so far. I just rewrite my timer driver implementation in csTimer coding style and it is right in the project codebase. I don't think it is suitable to use cubing.js or any other external npm library right now until all the project will be refactored and migrated to modern module and build system with npm packages.

If you want to have right implementation for GAN Smart Timer in cubing.js, feel free to take sources of my gan-web-blueooth library, and use any code, ideas and bluetooth protocol specs from there. My library is depends on rxjs, it is native event source for Angular applications. You may want to get rid of it and make pure Promise/callback/EventTarget version. If you wish I can help with it.

**Comment by afedotov** [comment]
About original csTimer and its author Chen Shuang, it is unknown what happined and why it is inactive. And will original repository and domain be maintained. cstimer.net is hosting together with cubingchina.com, probably need to contact someone from there and ask questions.

**Comment by afedotov** [comment]
Wow Chen Shuang is awoke and doing commits!
Going to rebase changes on current state of upstream master branch.
So this PR will be updated.
If Chen accepts my PR then, this one won't be needed, you can get this changes from upstream.

**Comment by afedotov** [comment]
Going to close this PR because its from wrong master branch that needs to be in sync with upstream.

**Pull request closed without merging**
